spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=postgres
spring.datasource.password=novasenha123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# chave secreta usada para assinar o JWT (pode ser qualquer string longa)
jwt.secret=minha-chave-super-secreta-troque-isso-em-producao-1234567890
jwt.expiration=86400000
